### ISSUE TITLE
Does nvenc work?

### ISSUE THREAD

**Issue by tyeeman** [tormyvancool/ffmpeg-4.1.3-shared-for-reaper#1]
Just getting into Reaper for video editing. I just installed the ffmpeg version Jon T suggests. I added ```-c:v hevc_nvenc``` to the command window and it was ignored. Does your's do the same or how can we make ffmpeg use nvenc?

**Comment by tormyvancool** [comment]
it's not an issue.

**Comment by tormyvancool** [comment]
Not planned, 'cause it's not an issue and it's no more useful on latest Reaper's versions
